name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Build project
        run: yarn install && npm run build

      - name: Deploy to LeanCloud
      - uses: manyuanrong/setup-lean-cli@v1.0.0
        with:
          version: '0.25.0'
      - run: 
          cd dist
          lean login --region us-w1 --username ${{secrets.LEANCLOUD_USER}} --password ${{secrets.LEANCLOUD_PASS}}
          lean switch --region us-w1 --group web ${{secrets.LEANCLOUD_APP_ID}}
          lean deploy
